import { tempItemType } from "./BoardIndex";

export const tempList : tempItemType[] = [ 
    {idx : '1' , 'title' : 'title1'},
    {idx : '2' , 'title' : 'title2'},
    {idx : '3' , 'title' : 'title3'},
    {idx : '4' , 'title' : 'title4'},
    {idx : '1' , 'title' : 'title1'},
    {idx : '2' , 'title' : 'title2'},
    {idx : '3' , 'title' : 'title3'},
    {idx : '4' , 'title' : 'title4'},
    {idx : '1' , 'title' : 'title1'},
    {idx : '2' , 'title' : 'title2'},
    {idx : '3' , 'title' : 'title3'},
    {idx : '4' , 'title' : 'title4'},
    {idx : '1' , 'title' : 'title1'},
    {idx : '2' , 'title' : 'title2'},
    {idx : '3' , 'title' : 'title3'},
    {idx : '4' , 'title' : 'title4'},
    {idx : '1' , 'title' : 'title1'},
    {idx : '2' , 'title' : 'title2'},
    {idx : '3' , 'title' : 'title3'},
    {idx : '4' , 'title' : 'title4'},
    {idx : '1' , 'title' : 'title1'},
    {idx : '2' , 'title' : 'title2'},
    {idx : '3' , 'title' : 'title3'},
    {idx : '4' , 'title' : 'title4'},
    {idx : '1' , 'title' : 'title1'},
    {idx : '2' , 'title' : 'title2'},
    {idx : '3' , 'title' : 'title3'},
    {idx : '4' , 'title' : 'title4'},
]